version: "3"

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web